# serverless.yml

service: desafio03

provider:
  name: aws
  runtime: nodejs12.x
  stage: fullcycle3
  region: us-east-1

functions:
  app:
    handler: index.handler
    events:
      - http: GET /
      - http: 'GET {proxy+}'